#ifndef CONSTANTS_H
#define CONSTANTS_H

#define VERSION 1
#define ID 1

// Удаляем переопределение ADC_RESOLUTION
#ifndef ADC_RESOLUTION
#define ADC_RESOLUTION 12
#endif

#define R_SENSE 0.075f
#define NUMBER_OF_JOINTS 6
#define MICROSTEP 32

#define MOTOR1_MAX_CURRENT 2000
#define MOTOR2_MAX_CURRENT 2000
#define MOTOR3_MAX_CURRENT 1900
#define MOTOR4_MAX_CURRENT 1700
#define MOTOR5_MAX_CURRENT 1700
#define MOTOR6_MAX_CURRENT 965

#endif