[env:mellow_fly_super8]
platform = ststm32
board = nucleo_h723zg
framework = arduino

extra_scripts = pre_build.py  ; Скрипт предсборки (если нужен)

build_flags =
    -D USB_VID=0x0483  ; VID USB
    -D USB_PID=0x5740  ; PID USB
    -D USB_MANUFACTURER="Mellow"  ; Производитель USB
    -D USB_PRODUCT="PAROL6 Robot"  ; Продукт USB
    -D ARDUINO_GENERIC_H723ZGTX  ; Конфиг платы
    -D USBCON  ; Включить USB
    -D STM32H723xx  ; Ядро MCU
    -D ARDUINO_USB_CDC_ON_BOOT=1  ; USB CDC на загрузке
    -D PC_3_C=PC3  ; Переопределение пина
    -D PC_2_C=PC2  ; Переопределение пина
    -Wno-builtin-macro-redefined  ; Игнор предупреждений
    -Wl,--allow-multiple-definition  ; Разрешить множественные определения

upload_protocol = stlink  ; Протокол загрузки
upload_port = /dev/ttyACM0  ; Порт загрузки
upload_speed = 921600  ; Скорость загрузки

lib_deps = 
    teemuatlut/TMCStepper@^0.7.3  ; Библиотека для TMC драйверов
    waspinator/AccelStepper @ ^1.64.0  ; Библиотека для управления шаговиками

monitor_port = ${env.upload_port}  ; Порт мониторинга
monitor_speed = 115200  ; Скорость мониторинга
monitor_rts = 0  ; RTS мониторинга
monitor_dtr = 0  ; DTR мониторинга